/** Types shared between `web/` and `api/`. */
import type { GuestRecord } from "./names";

// ===========================================================================
// RSVP v2 — identity by name search
// ===========================================================================
//
// The endpoints these describe:
//
//   SearchResponse     GET  /api/rsvp/search?q=
//   GuestMatch         one hit from that search
//   GuestDetail        GET  /api/rsvp/guest/:id
//   RsvpSubmission     POST /api/rsvp
//   RsvpSubmitResult   what that POST answers with

// ---------------------------------------------------------------------------
// Dietary
// ---------------------------------------------------------------------------

/**
 * The five options, and the only values `rsvps.dietary` and
 * `rsvps.plus_one_dietary` accept — there is a CHECK constraint in
 * db/schema.sql saying exactly this. Changing this union means a table
 * rebuild, not an ALTER, so it is worth getting right once.
 */
export type Dietary =
  | "halaal"
  | "vegetarian"
  | "vegan"
  | "pescatarian"
  | "none";

/**
 * One source for the form's buttons and the Worker's validation, so the UI
 * can never offer something the database will reject.
 */
export const DIETARY_OPTIONS = [
  { value: "none", label: "No restrictions" },
  { value: "halaal", label: "Halaal" },
  { value: "vegetarian", label: "Vegetarian" },
  { value: "vegan", label: "Vegan" },
  { value: "pescatarian", label: "Pescatarian" },
] as const satisfies readonly { value: Dietary; label: string }[];

export function isDietary(value: unknown): value is Dietary {
  return DIETARY_OPTIONS.some((o) => o.value === value);
}

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

/**
 * One hit from the name search.
 *
 * Built as an intersection with `GuestRecord` (shared/names.ts) so the
 * compiler guarantees a `GuestMatch[]` can be handed straight to
 * `searchGuests()`. If the matcher's input shape ever changes, this breaks
 * here rather than at runtime.
 *
 * WHAT IS DELIBERATELY ABSENT: email, phone, and the other members of the
 * household. `/api/rsvp/search` is unauthenticated by design — anyone may type
 * any name — so it must expose only what a guest needs to recognise
 * themselves. `householdLabel` is the single disambiguator, and it is
 * something a guest knows about themselves rather than something private.
 */
export type GuestMatch = GuestRecord & {
  /**
   * The guest's identifier everywhere outside the database — 16 hex
   * characters, generated by `db/schema.sql`.
   *
   * The integer primary key is never sent to a client. It is sequential, so it
   * would let anyone walk 1..N and read out the guest list; this cannot be
   * guessed, so `/api/rsvp/guest/:publicId` needs no other proof that the
   * caller has legitimately found this person.
   */
  publicId: string;
  middleName: string | null;
  /** `parties.label`, e.g. "The Banda Family". */
  householdLabel: string;
  allowPlusOne: boolean;
  /** Whether a reply is already on record. Not the reply itself. */
  hasResponded: boolean;
};

/**
 * `GET /api/rsvp/search?q=…`
 *
 * Always HTTP 200 except for a malformed request: "we could not find you" is a
 * normal outcome of a search, not an error condition.
 *
 *   match        exactly one confident hit -> go straight to the confirm card
 *   ambiguous    several equally good hits -> "which one is you?"
 *   suggestions  nothing matched, something is close -> "did you mean…?"
 *   none         nothing at all -> not-found + the reference contacts
 *
 * The matcher's internal `tier` and `score` are not carried on the wire. They
 * are logged server-side for tuning; the client only needs `kind`.
 */
export type SearchResponse =
  | { kind: "too-short"; minLength: number }
  | { kind: "none" }
  | { kind: "match"; guests: GuestMatch[] }
  | { kind: "ambiguous"; guests: GuestMatch[] }
  | { kind: "suggestions"; guests: GuestMatch[] };

// ---------------------------------------------------------------------------
// A reply on record
// ---------------------------------------------------------------------------

/**
 * An RSVP as the CLIENT is allowed to see it.
 *
 * `phone` is absent on purpose and must never be added. It is write-only:
 * the guest supplies it, the database stores it, the API never echoes it back.
 *
 * The reasoning: identity here is "your name is on the list", so anyone who
 * knows a guest's name can already reach that guest's RSVP — that is inherent
 * to the design and is an acceptable risk for a wedding. Reading back a phone
 * number is a different thing entirely. It is contact detail the guest gave us
 * for follow-up, not something they published, and handing it to anyone who
 * can spell their name would be a real leak rather than a tolerable one.
 *
 * The cost is that an amending guest re-enters their number. That is fine.
 */
export type RsvpRecord = {
  attending: boolean;
  /**
   * Whether a phone number is on file — not the number itself.
   *
   * The form needs this to say "we already have a number for you, leave the
   * field blank to keep it". Without it a returning guest cannot tell the
   * difference between "you never gave us one" and "we have one but won't show
   * you", and the blank field reads as data we lost.
   *
   * This discloses only that a guest supplied a number, which is a far smaller
   * thing than the number.
   */
  hasPhone: boolean;
  dietary: Dietary | null;
  dietaryNotes: string | null;
  plusOneName: string | null;
  plusOneDietary: Dietary | null;
  message: string | null;
  updatedAt: string;
};

/**
 * `GET /api/rsvp/guest/:id` — what step 3 needs about the confirmed guest,
 * including any reply to prefill from.
 */
export type GuestDetail = GuestMatch & {
  response: RsvpRecord | null;
};

// ---------------------------------------------------------------------------
// Submission
// ---------------------------------------------------------------------------

/**
 * Body of `POST /api/rsvp`.
 *
 * Keyed on the `publicId` the guest confirmed at step 2, rather than on a name
 * the server would have to re-resolve. The server still re-reads that
 * guest, so a fabricated id fails; it just never re-runs the fuzzy match, and
 * therefore can never resolve to a different person than the one the guest saw
 * on the confirmation card.
 */
export type RsvpSubmission = {
  /** The guest's `publicId`, as confirmed at step 2. */
  publicId: string;
  attending: boolean;
  /**
   * Phone / WhatsApp. Stored, never returned. See `RsvpRecord`.
   *
   * OMITTED means "leave whatever is on file alone" — which is what the form
   * sends when an amending guest leaves the field blank, since it was never
   * given the value to put there. An explicit empty string clears it.
   */
  phone?: string;
  dietary?: Dietary;
  dietaryNotes?: string;
  /** Requires the guest's `allowPlusOne`. Ignored when not attending. */
  plusOneName?: string;
  plusOneDietary?: Dietary;
  message?: string;
  /**
   * What the guest typed into the search box at step 1. Recorded in
   * `rsvp_events` only — never stored on the RSVP, never returned. It exists
   * so that "somebody replied as the wrong John Banda" is answerable after
   * the fact.
   */
  typedName?: string;
  /**
   * Set true to overwrite a reply already on record. Without it the API
   * refuses and returns `already_responded` with the existing reply, so a
   * stray double-submit can never quietly change an answer.
   */
  amend?: boolean;
};

export type RsvpErrorCode =
  /** missing or malformed fields */
  | "invalid_payload"
  /** no guest with that id */
  | "unknown_guest"
  /** a reply exists and `amend` was not set; `existing` is populated */
  | "already_responded"
  /** this guest is not permitted a plus-one */
  | "plus_one_not_allowed"
  /** dietary value outside the five allowed */
  | "invalid_dietary"
  | "internal_error";

export type RsvpSubmitSuccess = {
  ok: true;
  /** True when this call replaced a previous answer. */
  amended: boolean;
  guest: {
    publicId: string;
    firstName: string;
    middleName: string | null;
    lastName: string;
    householdLabel: string;
  };
  response: RsvpRecord;
};

export type RsvpSubmitError = {
  ok: false;
  error: RsvpErrorCode;
  message: string;
  /** Present for `already_responded`. */
  existing?: RsvpRecord;
};

export type RsvpSubmitResult = RsvpSubmitSuccess | RsvpSubmitError;

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export type RegistryItem = {
  id: number;
  name: string;
  description: string | null;
  image_url: string | null;
  item_url: string | null;
  price_cents: number;
  currency: string;
  target_count: number;
  pledged_count: number;
};

export type PledgePayload = {
  itemId: number;
  pledgeType: "item" | "cash";
  amountCents?: number;
  name: string;
  email?: string;
};
