#!/usr/bin/env node
/**
 * Turn a guest-list CSV into SQL, assigning each party a unique invite code.
 *
 *   node scripts/generate-codes.mjs ../db/guests.csv > ../db/guest-list.sql
 *
 * Or, to just print N codes (e.g. to write on paper invites by hand):
 *
 *   node scripts/generate-codes.mjs --count 40
 *
 * Expected CSV columns (header row required, order doesn't matter):
 *
 *   party        — how the invitation is addressed, e.g. "The Banda Family".
 *                  Rows sharing a party value go on the same invitation and
 *                  therefore share one code.
 *   first_name
 *   last_name
 *   plus_one     — optional; 1/yes/true to allow an unnamed plus-one
 *   invited_to   — optional; ceremony | reception | both (default: both)
 */
import { readFileSync } from "node:fs";
import { webcrypto as crypto } from "node:crypto";

const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const CODE_LENGTH = 6;

const used = new Set();

function generateCode() {
  for (;;) {
    const bytes = crypto.getRandomValues(new Uint8Array(CODE_LENGTH));
    let code = "";
    for (const b of bytes) code += ALPHABET[b % ALPHABET.length];
    if (!used.has(code)) {
      used.add(code);
      return code;
    }
  }
}

const sqlStr = (v) =>
  v === null || v === undefined || v === ""
    ? "NULL"
    : `'${String(v).replace(/'/g, "''")}'`;

/** Minimal CSV parser — handles quoted fields, embedded commas and newlines. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else quoted = false;
      } else field += c;
      continue;
    }
    if (c === '"') quoted = true;
    else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else field += c;
  }
  if (field !== "" || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((r) => r.some((cell) => cell.trim() !== ""));
}

const truthy = (v) => /^(1|y|yes|true)$/i.test(String(v ?? "").trim());

// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

if (args[0] === "--count") {
  const n = Number(args[1] || 10);
  for (let i = 0; i < n; i++) console.log(generateCode());
  process.exit(0);
}

const path = args[0];
if (!path) {
  console.error(
    "usage: generate-codes.mjs <guests.csv>\n" +
      "       generate-codes.mjs --count <n>",
  );
  process.exit(1);
}

const rows = parseCsv(readFileSync(path, "utf8"));
const header = rows[0].map((h) => h.trim().toLowerCase().replace(/\s+/g, "_"));
const col = (r, name) => {
  const i = header.indexOf(name);
  return i === -1 ? "" : (r[i] ?? "").trim();
};

const parties = new Map();

for (const r of rows.slice(1)) {
  const label = col(r, "party") || `${col(r, "first_name")} ${col(r, "last_name")}`.trim();
  if (!label) continue;

  if (!parties.has(label)) {
    parties.set(label, {
      code: generateCode(),
      invitedTo: col(r, "invited_to") || "both",
      guests: [],
    });
  }
  parties.get(label).guests.push({
    first: col(r, "first_name"),
    last: col(r, "last_name"),
    plusOne: truthy(col(r, "plus_one")),
  });
}

const out = [];
out.push("-- Generated by api/scripts/generate-codes.mjs");
out.push(`-- ${parties.size} parties, ${[...parties.values()].reduce((n, p) => n + p.guests.length, 0)} guests`);
out.push("");
out.push("INSERT INTO parties (code, label, invited_to) VALUES");
out.push(
  [...parties.entries()]
    .map(([label, p]) => `  (${sqlStr(p.code)}, ${sqlStr(label)}, ${sqlStr(p.invitedTo)})`)
    .join(",\n") + ";",
);
out.push("");
out.push("INSERT INTO guests (party_id, first_name, last_name, allow_plus_one)");
out.push("SELECT p.id, v.first_name, v.last_name, v.allow_plus_one FROM (");
out.push(
  [...parties.entries()]
    .flatMap(([, p]) =>
      p.guests.map(
        (g) =>
          `  SELECT ${sqlStr(p.code)} AS code, ${sqlStr(g.first)} AS first_name, ${sqlStr(g.last)} AS last_name, ${g.plusOne ? 1 : 0} AS allow_plus_one`,
      ),
    )
    .join("\n  UNION ALL\n"),
);
out.push(") v JOIN parties p ON p.code = v.code;");
out.push("");
out.push("-- Codes to print on the invitations:");
for (const [label, p] of parties) out.push(`--   ${p.code}  ${label}`);

console.log(out.join("\n"));
